-- Admin panel schema extensions

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TEST_SESSION_CONTROL';

ALTER TABLE "games" ADD COLUMN IF NOT EXISTS "minBet" DECIMAL(18,4);
ALTER TABLE "games" ADD COLUMN IF NOT EXISTS "maxBet" DECIMAL(18,4);

ALTER TABLE "game_sessions" ADD COLUMN IF NOT EXISTS "isTestMode" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "bots" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
